version: "3"

networks:
  default:

services:
  gislayer:
    build: ./
    hostname: gislayer
#    container_name: gislayer
    environment:
      TERM: 'xterm'
      GIS_REST_LAYER_CONF: '/srv/gislayer/tests/test_app.conf'
      HDX_GISDB_DB: testdb
      HDX_GISDB_USER: testuser
      HDX_GISDB_PASS: testpassword

    entrypoint: 'tail -f /dev/null'
  gisredis:
    image: unocha/alpine-redis:3.2.8
    hostname: gisredis
#    container_name: ${PREFIX}-${STACK}-gisredis
    environment:
      TERM: 'xterm'
  gisdb:
    image: postgis/postgis:11-3.2-alpine
    hostname: gisdb
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: testuser
      POSTGRES_DB: testdb

