#!/usr/bin/with-contenv sh

[ ! -z "$HDX_GISDB_ADDR" ] && export DB_HOST=$HDX_GISDB_ADDR
[ ! -z "$HDX_GISDB_PORT" ] && export DB_PORT=$HDX_GISDB_PORT
[ ! -z "$HDX_GISDB_DB" ]   && export DB_NAME=$HDX_GISDB_DB
[ ! -z "$HDX_GISDB_USER" ] && export DB_USER=$HDX_GISDB_USER
[ ! -z "$HDX_GISDB_PASS" ] && export DB_PASS=$HDX_GISDB_PASS

[ -z "$MONITOR_URL" ] && MONITOR_URL="/monitor"

# LOGGING_CONF_FILE needs to be set before substituting app.conf.tpl
export LOGGING_CONF_FILE=/srv/logging.conf

# regenerate app.conf
envsubst < /srv/gislayer/docker/app.conf.tpl > /srv/app.conf

# regenerate logging.conf
export LOG_LEVEL="${LOG_LEVEL:-INFO}"
[ ! -z "${LOG_LEVEL_CONSOLE}" ] || export LOG_LEVEL_CONSOLE=${LOG_LEVEL}
[ ! -z "${LOG_LEVEL_JSON}" ] || export LOG_LEVEL_JSON=${LOG_LEVEL}
[ ! -z "${LOG_LEVEL_TXT}" ] || export LOG_LEVEL_TXT=${LOG_LEVEL}
envsubst < /srv/gislayer/docker/logging.conf.tpl > /srv/logging.conf

cd /srv/gislayer
export GIS_REST_LAYER_CONF=/srv/app.conf

exec python3 gis_rest_layer.py
