#!/usr/bin/with-contenv sh

[ -z ${HDX_REDIS_WORKER_TTL} ] && HDX_REDIS_WORKER_TTL=600
[ -z ${HDX_REDIS_HOST} ]       && HDX_REDIS_HOST=gisredis
[ -z ${HDX_REDIS_PORT} ]       && HDX_REDIS_PORT=6379
[ -z ${HDX_REDIS_GISDB} ]      && HDX_REDIS_GISDB=1

WORKER_ID=$(ifconfig eth0 | grep inet | awk '{ print $2 }' | awk -F \: '{ print $2 }')

cd /srv/gislayer

exec ./hdxrq.py worker \
    --url redis://${HDX_REDIS_HOST}:${HDX_REDIS_PORT}/${HDX_REDIS_GISDB} \
    --name worker-${WORKER_ID} \
    --worker-ttl ${HDX_REDIS_WORKER_TTL} \
    geo_q analytics_q
